spring:
  application:
    name: config-server

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}:${server.port}
    #preferipAddress: true

  client: 
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

server:
  port: 8091