spring:
  application:
    name: admin-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    #preferipAddress: true

  client: 
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

server:
  port: 0

pivotal:
  loginservice:
    name: login-service
  employeeservice:
    name: employee-service